piranhacloud/piranha

- piranha-builder/pom.xml
- piranha-builder/src/main/java/com/manorrock/piranha/builder/WebApplicationBuilder.java
This module will contain classes for building Piranha artefacts using
the fluent/builder style
> Initial start for the builder module

- piranha/src/main/java/com/manorrock/piranha/DefaultDirectoryResource.java
> Fixes issue #120 - Add string ctor to DefaultDirectoryResource

- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestHttpServletRequest.java
- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestHttpServletResponse.java
> Fixes #122 - Added ctors taking full path to test request/response

- piranha-jsf-mojarra/src/main/java/com/manorrock/piranha/mojarra/MojarraInitializer.java
> Fixes #124 - Added flag to indicate Servlet added

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationRequest.java
> Fixes #138 co-variant return for ServletContext

- piranha-builder/src/main/java/com/manorrock/piranha/builder/WebApplicationBuilder.java
> #103 Small addition; build method for Filter

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> Fixes #141 - Default virtualServerName to "server"

- piranha-builder/src/main/java/com/manorrock/piranha/builder/WebApplicationBuilder.java
> #103 Builder methods for adding parameters and Servlet

- piranha-authentication-eleos/README.md
- piranha-authentication-eleos/pom.xml
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationFilter.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationInitializer.java
- pom.xml
- test/eleos/pom.xml
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/BasicAuthenticationTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/TestServerAuthModule.java
- test/pom.xml
> #145 Initial Eleos (Jakarta Authentication) support.

- piranha-api/src/main/java/com/manorrock/piranha/api/AuthenticatedIdentity.java
- piranha/src/main/java/com/manorrock/piranha/DefaultAuthenticatedIdentity.java
> Fixes #152 Initial version of authenticated identity

- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationInitializer.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/JakartaSecurityManager.java
> #145 Make use of AuthenticatedIdentity for simple authentication

- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
> Fixes #155 - Test web app with convenience methods

- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationFilter.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationInitializer.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/JakartaSecurityManager.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/programmatic/authentication/AuthenticateServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/programmatic/authentication/ProgrammaticAuthenticationTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/programmatic/authentication/TestServerAuthModule.java
> #145 Support for HttpServletRequest.authenticate

- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
> Fixes #158 method to security manager API to check data permission

- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
> Fixes #161 - Provide method to obtain unique application Id

- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationInitializer.java
- piranha-authorization-exousia/README.md
- piranha-authorization-exousia/pom.xml
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreFilter.java
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
- piranha-jakarta-security-base/README.md
- piranha-jakarta-security-base/pom.xml
- piranha-jakarta-security-base/src/main/java/com/manorrock/piranha/jakarta/security/base/JakartaSecurityManager.java
- piranha-jakarta-security-base/src/main/java/com/manorrock/piranha/jakarta/security/base/SecurityBaseInitializer.java
- piranha/src/main/java/com/manorrock/piranha/DefaultAuthenticatedIdentity.java
- piranha/src/test/java/com/manorrock/piranha/DefaultWebApplicationTest.java
- pom.xml
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/TestServerAuthModule.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/programmatic/authentication/ProgrammaticAuthenticationTest.java
- test/exousia/pom.xml
- test/exousia/src/test/java/com/manorrock/piranha/test/authorization/exousia/BasicConnectionTest.java
- test/exousia/src/test/java/com/manorrock/piranha/test/authorization/exousia/PublicServlet.java
- test/pom.xml
> #145 Split off JakartaSecurityManager to its own module and added authz

- test/eleos/pom.xml
> #145 Fix tests by not re-using forks.

- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
- piranha-authentication-eleos/pom.xml
- piranha-authorization-exousia/pom.xml
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationFilter.java
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationInitializer.java
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreFilter.java
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/PiranhaPrincipalMapper.java
- piranha-jakarta-security-base/pom.xml
- piranha-jakarta-security-base/src/main/java/com/manorrock/piranha/jakarta/security/base/JakartaSecurityManager.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationProtectedTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationPublicTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationStatelessTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicServerAuthModule.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/programmatic/authentication/ProgrammaticAuthenticationTest.java
#145 implemented full basic authentication cases and added tests
> #145 implemented full basic authentication cases and added tests

- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/CustomPrincipalProtectedTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/CustomPrincipalPublicTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/CustomPrincipalStatelessTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/CustomServerAuthModule.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/MyPrincipal.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/custom/principal/PublicServlet.java
- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
> #145 Added test cases for custom principle

- piranha-authorization-exousia/pom.xml
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/Application.java
> #145 Added support for constraint syntax as opposed to permission syntax

- piranha-authorization-exousia/pom.xml
- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationProtectedTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/BasicAuthenticationStatelessTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/elements/ApplicationWithElements.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/elements/BasicAuthenticationProtectedElementTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/elements/BasicAuthenticationPublicElementTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/elements/BasicAuthenticationStatelessElementTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/permissions/ApplicationWithPermissions.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/permissions/BasicAuthenticationProtectedPermissionTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/permissions/BasicAuthenticationPublicPermissionTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/basic/permissions/BasicAuthenticationStatelessPermissionTest.java
> Update to Exousia 0.4

- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
> Fixes #186 Allow security system to supply new request and response

- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationFilter.java
> #145 AuthenticationFilter uses optional new request/response

- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
- piranha-builder/src/main/java/com/manorrock/piranha/builder/AddFilterInitializer.java
- piranha-builder/src/main/java/com/manorrock/piranha/builder/WebApplicationBuilder.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
Fixes #189 Allow to set filters at specific order using builder
> #189 Allow to set filters at specific order using builder

- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #189 Merge conflict resolved, now staged

- piranha-authentication-eleos/pom.xml
- piranha-authorization-exousia/pom.xml
- piranha-jakarta-security-base/src/main/java/com/manorrock/piranha/jakarta/security/base/JakartaSecurityManager.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/DeclaredFilter.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/TestHttpServletRequestWrapper.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/TestHttpServletResponseWrapper.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/TestWrappingServerAuthModule.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/WrappingApplication.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/wrapping/WrappingTest.java
#145 Updated exousia to right version
> #145 Updated exousia to right version 

- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
Fixes #196 added postRequestProcess method
> #196 Allows security system post processing of the request

- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/ProtectedStatusCodesTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/PublicStatusCodesTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/status/codes/TestServerAuthModule.java
- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
#145 Added tests for status codes returned by auth module
> #145 Added tests for status codes returned by auth module

- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/BasicForwardTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/BasicIncludeTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/ForwardedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/IncludedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/TestServerAuthModule.java
#145 Added tests for forwarding and including
> #145 Added tests for forwarding and including

- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
> #207 Added support for cookies in test web app

- piranha-jakarta-security-base/src/main/java/com/manorrock/piranha/jakarta/security/base/JakartaSecurityManager.java
- pom.xml
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/MyPrincipal.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/RegisterSessionCustomPrincipalTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/RegisterSessionTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/register/session/TestServerAuthModule.java
#145 Added support for register sessions and added tests for that
> #145 Added support for register sessions and added tests for that

- piranha-api/src/main/java/com/manorrock/piranha/api/CurrentRequestHolder.java
- piranha-cdi-weld/pom.xml
- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/WeldContainer.java
- piranha/src/main/java/com/manorrock/piranha/DefaultCurrentRequestHolder.java
- piranha/src/main/java/com/manorrock/piranha/DefaultServletRequestDispatcher.java
- test/eleos/pom.xml
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/CDIBean.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/InvokeCDIBeanProtectedTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/InvokeCDIBeanPublicTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/invoke/cdi/TestServerAuthModule.java
- test/weld/.metadata/src/main/webapp/WEB-INF/faces-config.pageflow
#211 Track during a request what the current request instance is
> #211 Track during a request what the current request instance is

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
- piranha/src/test/java/com/manorrock/piranha/DefaultWebApplicationTest.java
> #213 Fix addServlet class override inconsistent with String version

- piranha-builder/src/main/java/com/manorrock/piranha/builder/AddServletInitializer.java
- piranha-builder/src/main/java/com/manorrock/piranha/builder/WebApplicationBuilder.java
- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/RealtimeHttpServletRequestWrapper.java
- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/WeldHttpServletRequest.java
- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/WeldInitListener.java
> #215 Adjust the Weld integration code to use request by reference

- test/eleos/pom.xml
- test/eleos/src/main/webapp/forward-cdi.xhtml
- test/eleos/src/main/webapp/forward.xhtml
- test/eleos/src/main/webapp/include-cdi.xhtml
- test/eleos/src/main/webapp/include.xhtml
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/Application.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/CDIForwardTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/CDIIncludeTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/ForwardedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/IncludedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/JSFCDIForwardTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/JSFCDIIncludeTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/JSFForwardTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/JSFIncludeTest.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/MyBean.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/ProtectedServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/PublicServlet.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/TestServerAuthModule.java
> #145 Add tests for dispatching to CDI using resource from auth module

- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/WeldInitListener.java
- piranha-cdi-weld/src/main/java/com/manorrock/piranha/weld/WeldInitializer.java
> #221 Initialize WELD earlier

- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/AuthenticationInitializer.java
- piranha-authentication-eleos/src/main/java/com/manorrock/piranha/authentication/elios/DoNothingServerAuthModule.java
> #145 Add default "do nothing" SAM.

- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
> #145 Extra comments

- piranha-jakarta-security-soteria/README.md
- piranha-jakarta-security-soteria/pom.xml
- piranha-jakarta-security-soteria/src/main/java/com/manorrock/piranha/jakarta/security/soteria/SoteriaInitializer.java
- pom.xml
> #224 Initial support for Soteria integration

- test/soteria/pom.xml
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/Application.java
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/BasicTest.java
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/DynamicInitialContextFactory.java
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/ProtectedServlet.java
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/PublicServlet.java
- test/soteria/src/test/java/com/manorrock/piranha/test/security/soteria/TestIdentityStore.java
- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
> #224 Added initial test for BASIC auth and Soteria

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationResponse.java
> #238 Set location header, absolute case

- test/test-utils/src/main/java/com/manorrock/piranha/test/utils/TestWebApp.java
> #239 Add method variants for POST and GET

- test/pom.xml
- test/soteria/basic/pom.xml
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/Application.java
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/BasicTest.java
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/DynamicInitialContextFactory.java
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/ProtectedServlet.java
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/PublicServlet.java
- test/soteria/basic/src/test/java/com/manorrock/piranha/test/security/soteria/auth/basic/TestIdentityStore.java
- test/soteria/form/pom.xml
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/Application.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/DynamicInitialContextFactory.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/ErrorPageServlet.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/FormTest.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/LoginPageServlet.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/ProtectedServlet.java
- test/soteria/form/src/test/java/com/manorrock/piranha/test/security/soteria/auth/form/TestIdentityStore.java
- test/soteria/pom.xml
#224 New FORM test and split up existing tests into modules for Soteria 
> #224 Added test for FORM authentication

- pom.xml
> #248 Added Tidy plugin, to be invoked manually

- tck/pom.xml
- tck/servlet/pom.xml
- test/classloader/pom.xml
- test/classloader2/pom.xml
- test/eleos/pom.xml
- test/exousia/pom.xml
- test/hazelcast/pom.xml
- test/jersey/pom.xml
- test/jpa/pom.xml
- test/mojarra/pom.xml
- test/myfaces/pom.xml
- test/openwebbeans/pom.xml
- test/pom.xml
- test/smallrye-health/pom.xml
- test/snoop/pom.xml
- test/soteria/basic/pom.xml
- test/soteria/form/pom.xml
- test/soteria/pom.xml
- test/springmvc/pom.xml
- test/struts/pom.xml
- test/test-utils/pom.xml
- test/vaadin/pom.xml
- test/weld/pom.xml
- test/wicket/pom.xml
> #248 Tidied poms not reachable from root

- pom.xml
> Organized and commented imports

- arquillian/pom.xml
- arquillian/server/pom.xml
- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerContainerConfiguration.java
- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerLoadableExtension.java
> #253 Base setup for Arquillian connector

- coverage/pom.xml
- piranha-resources-shrinkwrap/README.md
- piranha-resources-shrinkwrap/pom.xml
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ArchiveURLStreamHandler.java
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ShrinkWrapResource.java
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/StreamConnection.java
- piranha-resources-shrinkwrap/src/test/java/com/manorrock/piranha/shrinkwrap/DefaultResourceManagerTest.java
- pom.xml
> #259 Add support for ShrinkWrap resources

- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ShrinkWrapResource.java
- piranha-resources-shrinkwrap/src/test/java/com/manorrock/piranha/shrinkwrap/DefaultResourceManagerTest.java
> #259 Added alternative ctor to move eg classes to root

- piranha-api/src/main/java/com/manorrock/piranha/api/ResourceManagerClassLoader.java
- piranha/src/main/java/com/manorrock/piranha/DefaultResourceManagerClassLoader.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationClassLoader.java
> #262 Split-off ResourceManagerClassLoader

- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/IsolatingResourceManagerClassLoader.java
- piranha-resources-shrinkwrap/src/test/java/com/manorrock/piranha/shrinkwrap/DefaultWebApplicationClassLoaderTest.java
> #259 Added test loading a class from a Shrinkwrap archive

- piranha-api/src/main/java/com/manorrock/piranha/api/AnnotationManager.java
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/IsolatingResourceManagerClassLoader.java
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ShrinkWrapResource.java
- piranha-resources-shrinkwrap/src/test/java/com/manorrock/piranha/shrinkwrap/DefaultWebApplicationClassLoaderTest.java
- piranha/src/main/java/com/manorrock/piranha/DefaultAnnotationManager.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
- piranha/src/test/java/com/manorrock/piranha/DefaultAnnotationManagerTest.java
#259 Tmp: loading piranha and javax from sys classloader
> #259 Tmp: loading piranha and javax from sys classloader

- arquillian/server/pom.xml
- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- arquillian/server/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
> #253 Basic version of (somewhat) working arquillian connector

- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #278 Added getters/setters for annotation manager

- piranha-api/src/main/java/com/manorrock/piranha/api/Resource.java
- piranha-api/src/main/java/com/manorrock/piranha/api/ResourceManager.java
- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ShrinkWrapResource.java
- piranha/src/main/java/com/manorrock/piranha/DefaultAliasedDirectoryResource.java
- piranha/src/main/java/com/manorrock/piranha/DefaultDirectoryResource.java
- piranha/src/main/java/com/manorrock/piranha/DefaultJarResource.java
- piranha/src/main/java/com/manorrock/piranha/DefaultPrefixJarResource.java
- piranha/src/main/java/com/manorrock/piranha/DefaultResourceManager.java
> #280 Add API to retrieve all locations from resources

- piranha-api/src/main/java/com/manorrock/piranha/api/AnnotationManager.java
- piranha/src/main/java/com/manorrock/piranha/DefaultAnnotationManager.java
- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/JSFForwardTest.java
> #267 Add methods to get classes with given annotation

- piranha-api/src/main/java/com/manorrock/piranha/api/ResourceManagerClassLoader.java
- piranha/src/main/java/com/manorrock/piranha/DefaultResourceManagerClassLoader.java
> #283 Added method to obtain ResourceManager

- piranha-servlet/pom.xml
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/NaiveAnnotationScannerInitializer.java
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/ServletFeature.java
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebAnnotationInitializer.java
> #285 Add support for web annotation scanning and @WebServlet

- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/LiveObjectAnnotationScannerInitializer.java
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/ServletFeature.java
> #287 Scan additional web annotations next to WebServlet

- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebAnnotationInitializer.java
> #289 Support for @WebListener

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationServerOutputStream.java
> #291 Only write content-type header if contentType set

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationServerRequest.java
- piranha/src/test/java/com/manorrock/piranha/TestHttpServerRequest.java
> #293 Set correct method for ServerRequest

- piranha-resources-shrinkwrap/src/main/java/com/manorrock/piranha/shrinkwrap/ShrinkWrapResource.java
> #259 Improve copy algo for archive

- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebAnnotationInitializer.java
> #298 Add support for @WebFilter

- test/eleos/src/test/java/com/manorrock/piranha/test/authentication/eleos/dispatching/jsfcdi/CDIForwardTest.java
> #145 Ignore test for now, need to investigate

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationServerOutputStream.java
> #302 Support Secure and HttpOnly flags in cookies

- piranha-api/src/main/java/com/manorrock/piranha/api/HttpRequestManager.java
- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
- piranha/src/main/java/com/manorrock/piranha/DefaultHttpRequestManager.java
- piranha/src/main/java/com/manorrock/piranha/DefaultServletRequestDispatcher.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationRequest.java
- piranha/src/test/java/com/manorrock/piranha/DefaultHttpServletRequestTest.java
- piranha/src/test/java/com/manorrock/piranha/DefaultServletRequestDispatcherTest.java
- piranha/src/test/java/com/manorrock/piranha/DefaultWebApplicationTest.java
> #312 Added support to fire ServletRequestAttributeEvent

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #314 Added support to fire ServletContextAttributeEvent

- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebXml.java
> #318 Add SecurityConstraint to WebXml

- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebXml.java
- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebXmlInitializer.java
- piranha-servlet/src/test/java/com/manorrock/piranha/servlet/WebXmlInitializerTest.java
- piranha-servlet/src/test/webxml/test2/WEB-INF/web.xml
- piranha/src/main/java/com/manorrock/piranha/WebXml.java
> #323 Parsing of security constraints from web.xml

- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreFilter.java
> #340 Set context Id per request

- piranha-authorization-exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
> #346 Fix order handling empty permissions/constraints

- piranha-runner-war/src/main/java/com/manorrock/piranha/runner/war/PiranhaServerDeployer.java
> #355 Take servlet annotations from JANDEX.

- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXml.java
- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXmlInitializer.java
> #357 Added parsing of login-config from web.xml

- piranha-runner-war/src/main/java/com/manorrock/piranha/runner/war/PiranhaServerDeployer.java
- piranha-security-soteria/pom.xml
- piranha-security-soteria/src/main/java/com/manorrock/piranha/security/soteria/SoteriaPreCDIInitializer.java
- piranha-webxml/pom.xml
- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXmlInitializer.java
> #360 Passing web.xml login-conf details to Soteria

- piranha-security-soteria/src/main/java/com/manorrock/piranha/security/soteria/SoteriaPreCDIInitializer.java
> #365 Fix NPE

- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerDeployableContainer.java
> #367 Add beans.xml if not present

- piranha-runner-war/pom.xml
- piranha-runner-war/src/main/java/com/manorrock/piranha/runner/war/CdiExtension.java
- piranha-runner-war/src/main/java/com/manorrock/piranha/runner/war/InMemmoryIdentityStore.java
- piranha-runner-war/src/main/java/com/manorrock/piranha/runner/war/PiranhaServerDeployer.java
- piranha-runner-war/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- piranha-security-soteria/pom.xml
> #369 Added identity store for servlet auth mechanisms

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationServer.java
> #371 Set server port and name

- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXml.java
- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXmlInitializer.java
> #376 Added parsing web.xml deny-uncovered-http-methods

- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- piranha-api/src/main/java/com/manorrock/piranha/api/SecurityManager.java
- piranha-security-jakarta/src/main/java/com/manorrock/piranha/security/jakarta/JakartaSecurityManager.java
- piranha-security-soteria/src/main/java/com/manorrock/piranha/security/soteria/IdentityStoreLoginHandler.java
> #388 Added support for req.login, call identity store directly

- cdi/pom.xml
- embedded/pom.xml
- faces/pom.xml
- http/pom.xml
- nano/pom.xml
- security/pom.xml
- standard/pom.xml
> Running mvn tidy:pom

- pom.xml
> #404 Update Exousia to 0.4.2

- piranha-servlet/src/main/java/com/manorrock/piranha/servlet/WebAnnotationInitializer.java
- security/exousia/src/main/java/com/manorrock/piranha/authorization/exousia/AuthorizationPreInitializer.java
> #406 Add support for processing web security annotations

- piranha/src/main/java/com/manorrock/piranha/DefaultHttpSession.java
> #408 throw event and set valid to false in right order

- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXml.java
> #412 add ErrorPage to WebXml

- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXmlInitializer.java
> #411 Add support for parsing error pages

- piranha/src/main/java/com/manorrock/piranha/DefaultServlet.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #415 Added support for HTTP status code 404

- embedded/src/test/java/com/manorrock/piranha/embedded/EmbeddedPiranhaTest.java
- micro/src/test/java/com/manorrock/piranha/micro/MicroPiranhaTest.java
- piranha/src/main/java/com/manorrock/piranha/DefaultServlet.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplicationServer.java
- piranha/src/test/java/com/manorrock/piranha/DefaultWebApplicationRequestMapperTest.java
- piranha/src/test/java/com/manorrock/piranha/ServletTest.java
> #417 Support DefaultServlet for regular non filtered chain

- piranha-api/src/main/java/com/manorrock/piranha/api/WebApplication.java
- piranha-webxml/src/main/java/com/manorrock/piranha/webxml/WebXmlInitializer.java
- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #419 API to add error pages

- piranha/src/main/java/com/manorrock/piranha/DefaultWebApplication.java
> #421 Forward to error page on error code or exception

- security/soteria/src/main/java/cloud/piranha/security/soteria/SoteriaPreCDIInitializer.java
> Updated to use new way to obtain WebXml

- security/exousia/src/main/java/cloud/piranha/authorization/exousia/AuthorizationPreInitializer.java
- servlet/webxml/src/main/java/cloud/piranha/servlet/webxml/WebXmlInitializer.java
> #432 Use WebXml to get constraints

- arquillian/pom.xml
- pom.xml
> #434 Add arquillian module to main pom

- .travis.yml
- arquillian/server/src/main/java/com/manorrock/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- micro/src/main/java/com/manorrock/piranha/micro/PiranhaServerDeployer.java
- test/arquillian/pom.xml
> #253 Fix Arquillian tests

- microprofile/smallrye/pom.xml
- piranha/pom.xml
- resource/shrinkwrap/pom.xml
- standard/pom.xml
> mvn tidy:pom run

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranhaBuilder.java
> #459 added buildAndStart method

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedRequestBuilder.java
> #465 Added header method

- security/soteria/src/main/java/cloud/piranha/security/soteria/DynamicInitialContextFactory.java
> #467 Add dynamic context factory

- security/soteria/src/main/java/cloud/piranha/security/soteria/DynamicInitialContextFactory.java
> #467 Update date in header

- security/jakarta/src/main/java/cloud/piranha/security/jakarta/JakartaSecurityManager.java
> #470 Set a null in request and context

- security/jakarta/src/main/java/cloud/piranha/security/jakarta/JakartaSecurityAllInitializer.java
> #472 Initializer that sets the full security pipeline

- security/soteria/pom.xml
> #467 Updated poms

- security/jakarta/pom.xml
> #472 Updated pom

- security/soteria/pom.xml
This reverts commit 1d94e34bb798f2c60fb21b48e768954162172acd.
> Revert "Revert "#467 Updated poms""

- security/jakarta/src/main/java/cloud/piranha/security/jakarta/JakartaSecurityManager.java
This reverts commit 49042ed670fd7c207ba8fe89076ceae318db5094.
> Revert "Revert "#470 Set a null in request and context""

- microprofile/omnifaces/jwt/README.md
- microprofile/omnifaces/jwt/pom.xml
- microprofile/omnifaces/jwt/src/main/java/cloud/piranha/omnifaces/jwt/OmniFacesJwtIntegrator.java
- microprofile/omnifaces/jwt/src/main/resources/META-INF/beans.xml
- microprofile/omnifaces/jwt/src/main/resources/META-INF/services/org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable
- microprofile/omnifaces/pom.xml
> #483 Integrate OmniFaces JWT

- api/src/main/java/cloud/piranha/api/AnnotationManager.java
- piranha/src/main/java/cloud/piranha/DefaultAnnotationManager.java
> #492 Add support for instances (instanceof for certain type)

- micro/pom.xml
- micro/src/main/java/cloud/piranha/micro/PiranhaServerDeployer.java
- pom.xml
- rest/jersey/README.md
- rest/jersey/pom.xml
- rest/jersey/src/main/java/cloud/piranha/rest/jersey/JerseyInitializer.java
- rest/pom.xml
> #501 Add a Jersey integration module

- cdi/weld/pom.xml
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldSecurityService.java
> #503 Implement Weld SPI to inject Principal

- cdi/weld/src/main/resources/META-INF/services/org.jboss.weld.bootstrap.api.Service
> #503 Services file to activate SPI

- micro/pom.xml
- microprofile/omnifaces/jwt/pom.xml
- pom.xml
- rest/jersey/pom.xml
> #507 Add CDI / HK2 bridge dependency

- arquillian/server/pom.xml
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerContainerConfiguration.java
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
> #526 Added initial config options for Arquillian

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerContainerConfiguration.java
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- test/eleos/src/test/java/cloud/piranha/test/eleos/dispatching/jsfcdi/CDIForwardTest.java
> #526 Using option for remote repo

- arquillian/pom.xml
- arquillian/server/pom.xml
> #530 Remove parent for Arquillian pom and flatten

- piranha/src/main/java/cloud/piranha/DefaultWebApplication.java
> #532 Invoke filter chain when there's a chain but no Servlet

- piranha/src/main/java/cloud/piranha/DefaultFilterChain.java
- piranha/src/test/java/cloud/piranha/DefaultWebApplicationTest.java
- test/eleos/src/test/java/cloud/piranha/test/eleos/dispatching/jsfcdi/JSFForwardTest.java
> #534 Send 404 at end of chain and Servlet null

- arquillian/server/.gitignore
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationRequest.java
> #536 Tracking bytes read from read()

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
> #542 Add update policy for external maven repos

- pom.xml
Fixes #544 getting default Policy multiple times
> #544 Update to Exousia 0.4.3

- api/src/main/java/cloud/piranha/api/FilterPriority.java
> #546 Add interface to indicate priority of Filters

- piranha/src/main/java/cloud/piranha/DefaultWebApplication.java
> #548 Utilise filter priorities when creating filter chain

- security/eleos/src/main/java/cloud/piranha/security/elios/AuthenticationFilter.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationFilter.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreFilter.java
> #550 Assigned priority to security filters

- api/src/main/java/cloud/piranha/api/WebApplication.java
- api/src/main/java/cloud/piranha/api/WebApplicationRequestMapper.java
- piranha/src/main/java/cloud/piranha/DefaultFilterEnvironment.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplication.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationRequestMapper.java
> #100 Implement addMappingForUrlPatterns

- piranha/src/main/java/cloud/piranha/DefaultHttpSessionManager.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationRequest.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationResponse.java
> #553 Support Path attribute when writing out cookies

- micro/src/main/java/cloud/piranha/micro/PiranhaBeanArchiveHandler.java
> #555 Limiting handler to WEB_INF/classes references

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerContainerConfiguration.java
> #558 Merge external dependencies for Arquillian connector

- micro/pom.xml
- micro/src/main/java/cloud/piranha/micro/PiranhaServerDeployer.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/GlobalArchiveStreamHandler.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/NodeURLStreamHandler.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapDirectoryInputStream.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java
- test/eleos/src/test/java/cloud/piranha/test/eleos/dispatching/jsfcdi/CDIForwardTest.java
> #560 Adding stream handlers for shrinkwrap archive

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/StaticStreamHandler.java
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/StaticURLStreamHandlerFactory.java
- micro/src/main/java/cloud/piranha/micro/PiranhaServerDeployer.java
> #562 Make setting url stream handler repeatable

- faces/mojarra/src/main/java/cloud/piranha/faces/mojarra/MojarraInitializer.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplication.java
> Check if URL protocol is "file" for getRealPath and Add *.jsf mapping

- piranha/src/main/java/cloud/piranha/DefaultWebApplicationRequest.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationServer.java
> #567 Read body for FORM encoded and PUT requests

- security/eleos/src/main/java/cloud/piranha/security/elios/AuthenticationFilter.java
> #569 Default error response for auth failures

- piranha/src/main/java/cloud/piranha/DefaultWebApplicationRequest.java
- piranha/src/main/java/cloud/piranha/DefaultWebApplicationServer.java
> #567 Try read body after request, use read() method for reading

- piranha/src/main/java/cloud/piranha/DefaultResourceManagerClassLoader.java
> #573 thread-safety improvements for class loader

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerContainerConfiguration.java
- micro/pom.xml
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java
> Bring Micro via Arquillian back to life

- micro/src/test/java/cloud/piranha/micro/MicroPiranhaIT.java
> Being worked on. WIP

- arquillian/server/pom.xml
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerLoadableExtension.java
- micro/pom.xml
- micro/src/main/java/cloud/piranha/micro/InMemmoryIdentityStore.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- micro/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroPiranha.java
- micro/src/main/java/cloud/piranha/micro/StaticStreamHandler.java
- micro/src/main/java/cloud/piranha/micro/StaticURLStreamHandlerFactory.java
> #747 Moved micro classes from arquillian package to micro

- micro/pom.xml
- micro/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- webapp/pom.xml
- webapp/webannotation/pom.xml
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webservlet/WebAnnotationInitializer.java
- webapp/webannotation/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
- webapp/webservlet/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
> #754 Renamed WebServletInitializer to WebAnnotationInitializer

- extension/apachewebprofile/pom.xml
- extension/servlet/pom.xml
- extension/tomcat9/pom.xml
- extension/webprofile/pom.xml
- webapp/webannotation/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
> #756 Removed service file and fixed poms

- extension/micro-servlet/pom.xml
- extension/micro-servlet/src/main/java/cloud/piranha/extension/micro/servlet/MicroServletExtension.java
- extension/micro-servlet/src/main/java/cloud/piranha/extension/micro/servlet/package-info.java
- extension/micro-servlet/src/main/resources/META-INF/services/cloud.piranha.webapp.api.WebApplicationExtension
- extension/pom.xml
- micro/pom.xml
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- micro/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- resource/shrinkwrap/pom.xml
> #765 Make Micro runner a slim jar loading Piranha servlet via extension

- resource/impl/src/main/java/cloud/piranha/resource/DefaultResourceManagerClassLoader.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/IsolatingResourceManagerClassLoader.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationClassLoader.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationClassLoaderTest.java
> #775 moved DefaultResourceManagerClassLoader to resource impl

- extension/micro-servlet/pom.xml
> #787 Include XML Binding in Micro Servlet

- cdi/weld/pom.xml
> Fixes issue #771 - Include Jakarta Annotation jar in Piranha Server

- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpServer.java
> Fixes issue #792 - Fix typo

- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletResponseTest.java
I don't know for sure if the charset of Content Type must be always lowercase.
> Fixes issue #796 - Add positive / negative test for writeContentType

- bom/pom.xml
- extension/apachewebprofile/pom.xml
- extension/webprofile/pom.xml
> Fixes issue #799 - Jakarta JSON Processing and Jakarta JSON Binding

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> Fixes issue #807 - NPE while writing cookie without value

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
> Fixes issue #804 - Refactor DefaultWebApplicationServer.createRequest

- resource/impl/src/main/java/cloud/piranha/resource/DirectoryResource.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
Maybe we need to revisit this issue to validate better how it will work with Piranha Micro, because it uses the Shrinkwrap protocol.
Fixes #769
> Fixes issue #769 - Implement DefaultWebApplication.getResourcePaths

- extension/micro-core/pom.xml
- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroPiranha.java
- upload/apache/pom.xml
> #790 bring back MICRO_PIRANHA.

- micro/src/main/java/cloud/piranha/micro/MicroPiranha.java
> #791 Add support for exploded apps via --webapp

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> #819 Fixed path info getting corrupted

- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerRequest.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
> Fixes issue #814 - Fix Javadocs

- cdi/openwebbeans/src/main/java/cloud/piranha/cdi/openwebbeans/OpenWebBeansObjectInstanceManager.java
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldObjectInstanceManager.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperExtension.java
- pages/jasper/src/test/java/cloud/piranha/pages/jasper/JasperInitializerTest.java
- servlet/api/src/test/java/javax/servlet/TestServletRequest.java
- webapp/annotationscan/src/main/java/cloud/piranha/webapp/annotationscan/AnnotationScanExtension.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultMultiPartManager.java
- webapp/tempdir/src/main/java/cloud/piranha/webapp/tempdir/TempDirExtension.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlExtension.java
> Fixes issue #816 - Fix generics

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
> Fixes issue #811 - getResourcePaths should not accept file as input

- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreInitializer.java
Fixes #821
TODO: the connection between the annotation processor here and the
consumer should be improved.
> #821 Use the right constant for now

- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java
#823 Adds the web-inf/lib archives to the web-inf class loader.
(not indexed yet)
> #823 Adding web-inf/lib archives.

- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
> #823 Add jar files from web-inf/lib to index

- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServer.java
- http/grizzly/src/main/java/cloud/piranha/http/grizzly/GrizzlyHttpServer.java
- http/grizzly/src/main/resources/META-INF/services/cloud.piranha.http.api.HttpServer
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServer.java
- http/impl/src/main/resources/META-INF/services/cloud.piranha.http.api.HttpServer
- http/netty/src/main/java/cloud/piranha/http/netty/NettyHttpServer.java
- http/netty/src/main/resources/META-INF/services/cloud.piranha.http.api.HttpServer
- http/singlethread/src/main/java/cloud/piranha/http/singlethread/SingleThreadHttpServer.java
- http/singlethread/src/main/resources/META-INF/services/cloud.piranha.http.api.HttpServer
- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpServer.java
- http/undertow/src/main/resources/META-INF/services/cloud.piranha.http.api.HttpServer
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- micro/src/main/java/cloud/piranha/micro/MicroPiranha.java
> Fixes issue #721 - Support --http on Piranha Micro

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServerRequest.java
- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServerResponse.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServerResponse.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerResponse.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationResponse.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> #829 Flush and close async response

- bom/pom.xml
> Fixes issue #832 - Move dependencies version to parent BOM

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
#829 Don't try to test passed in response, but rather use the underlying one.
> #829 close the underlying response

- security/eleos/README.md
> Fixes issue #840 - Fix typo Elios -> Eleos

- http/singlethread/src/test/java/cloud/piranha/http/singlethread/SingleThreadHttpServerTest.java
> Fixes issue #854 - Fix SingleThread HTTP server tests

- arquillian/test/servlet-basic/src/test/java/cloud/piranha/test/arquillian/ServletBasicTest.java
> Fixes issue #855 - Fix ServletBasicTest

- http/singlethread/src/test/java/cloud/piranha/http/singlethread/SingleThreadHttpServerTest.java
Reverts piranhacloud/piranha#863
> Revert "Fixes issue #854 - Fix SingleThread HTTP server tests"

- test/pom.xml
> Also remove tests from pom

- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroPiranha.java
> Fixes issue #872 - Use the original archive name for Shrinkwrap archives

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncNonHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> Fix typo in classname

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncNonHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #829 Implemented wrapper swap for async HTTP dispatches

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #829 Rudimentary support for async invoke with ServletRequest

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> #829 Added guard against multiple invocations of startAsync

- CODE_CONVENTIONS.md
- SECURITY.md
> Fixes issue #892 - Fix typos in docs

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServerProcessor.java
- http/api/src/test/java/cloud/piranha/http/api/HttpServerTest.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerProcessingThread.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerProcessor.java
> #894 Replace stateful getter with return from process method.

- server/src/main/java/cloud/piranha/server/ServerPiranha.java
> #896 Continue deploying upon init/start exception in Server

- bom/pom.xml
- cdi/weld/pom.xml
> Replaced snapshot versions with published milestones

- session/hazelcast/pom.xml
- session/hazelcast/src/main/java/cloud/piranha/session/hazelcast/HazelcastInitializer.java
- session/hazelcast/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
- session/hazelcast/src/test/java/cloud/piranha/session/hazelcast/HazelcastInitializerTest.java
> Fixes issue #916 - Add ServletContainerInitializer to Hazelcast Session module

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletRequestTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/HttpServletRequestTest.java
Partially fixes #912 
I could not get to fix the getRequestDispatcherTest, more info at https://github.com/piranhacloud/piranha/issues/912#issuecomment-651514704
> Fixes issue #912 - Fix failures when running TCK Sample "ServletRequestTest"

- test/webxml/web-fragment-in-jar-webapp/src/main/webapp/index.html
> Fixes issue #921 - Fix SonarCloud reliability issue

- appserver/rest/pom.xml
> Fixes issue #927 - Rename artifact pirnaha-appserver-rest -> piranha-appserver-rest

- servlet/api/src/main/java/javax/servlet/Filter.java
- servlet/api/src/main/java/javax/servlet/GenericFilter.java
> #929 Implemented GenericFilter methods

- bom/pom.xml
> Fixes issue #876 - Fix Jakarta Pages TCK pipeline

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXml.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlFilter.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlFilterMapping.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> #934 Refactored FilterMapping to be compliant with XSD definition

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/ServletTest.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> #939 Added basic support for servlet-name in filter mappings.

- bom/pom.xml
- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- extension/micro-profile/pom.xml
- extension/micro-profile/src/main/java/cloud/piranha/extension/micro/profile/MicroProfileExtension.java
- extension/micro-profile/src/main/resources/META-INF/services/cloud.piranha.webapp.api.WebApplicationExtension
- extension/pom.xml
I'd like some review about REST annotations, I couldn't understand why they were disabled to handle later. Maybe @arjantijms can give some hints?
Fixes #936
> Fixes issue #936 - Implement micro-profile extension

- external/tck/microprofile/jwt/pom.xml
- external/tck/microprofile/jwt/suite/pom.xml
- external/tck/microprofile/pom.xml
> Fixes issue #932 - Fix MicroProfile JWT TCK pipeline

- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
> #952 Moved security-constraint parsing to WebXMLParser

- bom/pom.xml
> #955 Update to Exousia to 0.4.4

- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
> #957 load piranha-callers.xml from file in archive

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServlet.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServletSecurityRoleRef.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
> #959 parse security-role-ref and add insances to Servlet class

- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
> #961 Workaround for annotation classes crashing startup

- external/tck/microprofile/jwt/test/pom.xml
> #967 update to 20.8.0

- pom.xml
> Fixes issue #972 - Failsafe M5 don't find any tests in JWT TCK

- micro/pom.xml
- test/snoop/pom.xml
- test/tyrus/pom.xml
> Fixes issue #869 - Change Piranha Micro module to only distribute shaded JAR

- bom/pom.xml
- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranhaBuilder.java
- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreInitializer.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/PiranhaToExousiaConverter.java
- security/jakarta/src/main/java/cloud/piranha/security/jakarta/JakartaSecurityManager.java
- test/arquillian/pom.xml
- test/arquillian/servlet-basic/src/test/java/cloud/piranha/test/arquillian/ServletBasicIT.java
- test/omnifaces-jwt/pom.xml
- test/omnifaces-jwt/src/main/webapp/WEB-INF/web.xml
- test/omnifaces-jwt/src/test/java/cloud/piranha/test/microprofile/omnifaces/jwt/JwtTest.java
- test/soteria/basic/src/test/java/cloud/piranha/test/soteria/basic/BasicTest.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/SecurityManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterChain.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultSecurityManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXml.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/TestWebApplicationRequest.java
- webapp/webannotation/pom.xml
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webservlet/WebAnnotationInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
Add support for handling security-role-ref in web.xml and added support for processing explicit and implicit role names.
> 976 security role ref

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/ServletContainerInitializerTest.java
> Fixes issue #714 - Add HandlesTypes functionality

- extension/servlet/pom.xml
- server/pom.xml
- webapp/api/src/main/java/cloud/piranha/webapp/api/SecurityManager.java
> #994 Fix startup failure in Server

- extension/microprofile/pom.xml
- maven/plugins/micro/pom.xml
- test/arquillian/pom.xml
- test/embedded/pom.xml
- test/pom.xml
- test/soteria/basic/pom.xml
- test/soteria/form/pom.xml
- test/vaadin/pom.xml
- test/webxml/pom.xml
- test/webxml/web-fragment-in-jar-test/pom.xml
- test/webxml/web-fragment-in-jar-webapp/pom.xml
- test/webxml/web-fragment-in-jar/pom.xml
> Mini tyding of poms

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
> #1006 Implemented hasOriginalRequestAndResponse

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
> #1012 - Implement async dispatch once per cycle

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> #1014 - New asyncContext after dispatch

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1018 Don't flush response buffer after async dispatch

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletRequestTest.java
> #1020 Fail fast when request/response is null

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
> #1023 Always flush buffer on complete, not only when not commmitted

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
> 1025 - Fix setting response in async wrapper

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- extension/micro-core/src/main/java/cloud/piranha/micro/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
> #1027 Restored option to use custom context root for Micro

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/FilterMapping.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplication.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequestMapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterMapping.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> #1029 Add DispatchType to APIs

- extension/webprofile/src/main/java/cloud/piranha/extension/webprofile/WebProfileExtension.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletEnvironment.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletInvocation.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequestMapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterMapping.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
> #1031 - Unify service and dispatch logic - step 1

- webapp/api/src/main/java/cloud/piranha/webapp/api/FilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> #1044 - Include welcome files and filters to servlet invocation

- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> 1046 factor out invocation finder

- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/ServletTest.java
> #1063 - implement error page forwarding with attributes set

- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerProcessingThread.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
Fixes #1065
Needs more research to properly fix.
> #1065 - mitigate connection reset on the client.

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1063 - Fix potential NPE

- pom.xml
- transaction/api/pom.xml
- transaction/api/src/main/java/module-info.java
- transaction/api/src/test/java/javax/transaction/test/HeuristicCommitExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/HeuristicMixedExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/HeuristicRollbackExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/InvalidTransactionExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/NotSupportedExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/RollbackExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/SystemExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/TestTransactional.java
- transaction/api/src/test/java/javax/transaction/test/TransactionRequiredExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/TransactionRollbackExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/TransactionalExceptionTest.java
- transaction/api/src/test/java/javax/transaction/test/TransactionalTest.java
- transaction/api/src/test/java/javax/transaction/test/module-info.java
- transaction/nonxa/pom.xml
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/DefaultTransactionManagerTest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/DefaultTransactionTest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/DefaultUserTransactionTest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/EclipseLinkSessionCustomizer.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/JPA2DatabasesTest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/JPADatabaseTest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/JPATest.java
- transaction/nonxa/src/test/java/cloud/piranha/transaction/nonxa/test/module-info.java
- transaction/nonxa/src/test/resources/META-INF/persistence.xml
> #1071 - Move tx tests to .test folder and adjust modules

- extension/jakartaee/src/main/java/cloud/piranha/extension/jakartaee/JakartaEEExtension.java
- extension/micro/src/main/java/cloud/piranha/extension/micro/MicroExtension.java
- extension/servlet/src/main/java/cloud/piranha/extension/servlet/ServletExtension.java
- extension/tomcat9/src/main/java/cloud/piranha/extension/tomcat9/Tomcat9Extension.java
- extension/webprofile/src/main/java/cloud/piranha/extension/webprofile/WebProfileExtension.java
- microprofile/omnifaces/jwt/src/main/java/cloud/piranha/microprofile/omnifaces/jwt/OmniFacesJwtIntegrator.java
- microprofile/omnifaces/jwt/src/main/java/module-info.java
- microprofile/omnifaces/jwt/src/main/resources/META-INF/services/org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable
- microprofile/smallrye/health/src/main/java/cloud/piranha/microprofile/smallrye/health/SmallRyeHealthServlet.java
- microprofile/smallrye/health/src/main/java/cloud/piranha/microprofile/smallrye/health/SmallRyeLivenessServlet.java
- microprofile/smallrye/health/src/main/java/cloud/piranha/microprofile/smallrye/health/SmallRyeReadinessServlet.java
- test/omnifaces-jwt/src/test/java/cloud/piranha/test/microprofile/omnifaces/jwt/JwtTest.java
- test/smallrye-health/src/test/java/piranha/cloud/test/smallrye/health/SmallRyeHealthTest.java
- test/smallrye-health/src/test/java/piranha/cloud/test/smallrye/health/SmallRyeLivenessTest.java
- test/smallrye-health/src/test/java/piranha/cloud/test/smallrye/health/SmallRyeReadinessTest.java
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationExtension.java
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationInitializer.java
- webapp/webannotation/src/main/java/module-info.java
> Fixes issue #1074 - Rename packages to align with module name

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
> Fixes issue #1076 - Fix adding dynamic filters

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterChain.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1078 - Apply filters to all dispatch types

- .github/workflows/codeql-analysis.yml
> Fixes issue #1080 - Change build command for CodeQL

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> #1082 Commit response when printwriter is flushed

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
Fixes #1085
I have added some null argument checking too. If it is better I can extract to another issue and PR.
> Fixes issue #1085 - Don't allow JSP and session timeout updates after initialized

- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/test/java/cloud/piranha/webapp/webxml/WebXmlParserTest.java
- webapp/webxml/src/test/webxml/parse4/WEB-INF/web.xml
> Fixes issue #1092 - Allow multi url-patterns in servlet-mapping

- extension/servlet/src/main/java/cloud/piranha/extension/servlet/ServletExtension.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperJspManager.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperServlet.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServlet.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1096 - Add implementation for jsp-file tag in servlet declaration

- extension/micro/pom.xml
- extension/micro/src/main/java/cloud/piranha/extension/micro/MicroExtension.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/scinitializer/src/main/java/cloud/piranha/webapp/scinitializer/ServletContainerInitializerExtension.java
Adjusted some parts of the code to play nice with Micro already
installing the security bits.
> #1108 - Added ServletContainerInitializerExtension to Micro

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> Fixes #1110 - Set dispatcher type when using the include dispatcher type

- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationInitializer.java
Fixes #1112
Once in tainted mode, various methods from ServletContext will start
throwing exceptions.
> #1112 - Introduced tainted mode

- nano/src/test/java/cloud/piranha/nano/NanoResponseTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletResponseTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/HttpServletResponseTest.java
> Fixes #1117 - Fix value of date header

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> #1119 - Enforce ServletContext#getResource param starts with slash

- upload/apache/pom.xml
> #1121 - Generate source jar for shaded apache upload

- overview.md
- shared/database-property.md
> Fixes issue #1115 - Document Piranha Database Property driver

- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXml.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/FilterTest.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> #1128 - Implement Servlet effective major/minor version

- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/test/java/cloud/piranha/webapp/webxml/WebXmlParserTest.java
- webapp/webxml/src/test/webxml/parse3/WEB-INF/web.xml
> Fixes issue #1130 - Parse multi welcome-files

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> #1132 - Track ServletContext source and prevent addFilter when wrong.

- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperJspManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> 1132 track servletcontext

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServer.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerAcceptorThread.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerProcessingThread.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerProcessor.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerRequest.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerThreadFactory.java
- http/netty/src/main/java/cloud/piranha/http/netty/NettyHttpServerHandler.java
- http/netty/src/main/java/cloud/piranha/http/netty/NettyHttpServerInitializer.java
- http/singlethread/src/main/java/cloud/piranha/http/singlethread/SingleThreadHttpServer.java
- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpServer.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- monitor/jmx/src/main/java/cloud/piranha/monitor/jmx/JMXServerInitializer.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperInitializer.java
- server/src/main/java/cloud/piranha/server/ServerPiranha.java
- upload/apache/src/main/java/cloud/piranha/upload/apache/ApacheMultiPartInitializer.java
- upload/apache/src/main/java/cloud/piranha/upload/apache/ApacheMultiPartManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultMultiPartManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/scinitializer/src/main/java/cloud/piranha/webapp/scinitializer/ServletContainerInitializerExtension.java
- webapp/tempdir/src/main/java/cloud/piranha/webapp/tempdir/TempDirInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1136 - Remove LOGGER.isLoggable checks

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/ServletTest.java
> #1138 - handle permanent unavailable exception in Servlet

- api/pom.xml
- cli/pom.xml
- database/environment/pom.xml
- database/property/pom.xml
- http/test-api/pom.xml
- resource/shrinkwrap/pom.xml
- server/pom.xml
- war/jmx/pom.xml
- war/pom.xml
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
> 1144 Added guard to addServlet

- webapp/api/src/main/java/cloud/piranha/webapp/api/FilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlFilter.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
- webapp/webxml/src/test/java/cloud/piranha/webapp/webxml/WebXmlParserTest.java
- webapp/webxml/src/test/webxml/parse/WEB-INF/web.xml
> Fixes issue #1147 - Add async-supported to filters

- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationInitializer.java
> Fixes issue #1150 - Add async-supported to WebServlet and WebFilter annotations

- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationInitializer.java
> Fixes issue #1154 - Use the full class name if the WebAnnotations don't provide the name attribute

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapperTest.java
> Fixes issue #1156 - Prefix servlet mapping is matching wrong requests

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- micro/src/main/java/cloud/piranha/micro/MicroDeployOutcome.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
> #1149 - Use map for Micro parameters

- .github/workflows/release.yml
- pom.xml
> Fixes issue #1070 - Change over to use Java 15

- security/eleos/src/main/java/cloud/piranha/security/eleos/AuthenticationInitializer.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationInitializer.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreInitializer.java
> Fixes issue #1161 - Add async-supported to security filters

- .github/workflows/codeql-analysis.yml
> Fixes issue #1160 - Change CodeQL to run only weekly

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultMimeTypeManager.java
> #1165 - Added extra mimetypes

- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperExtension.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperInitializer.java
- pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperServlet.java
Fixes #1167
Some small formatting and cleanup
> #1167 - Name Jasper servlet "jsp"

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpSessionManagerTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
Fixes issue #1169 
Also throws null first in setInitParameter
> Fixes issue #1169 - Set the default value of effective session tracking to the default session tracking

- appserver/api/src/main/java/cloud/piranha/appserver/api/WebApplicationServerRequest.java
- appserver/api/src/main/java/cloud/piranha/appserver/api/WebApplicationServerResponse.java
- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServerRequest.java
- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServerResponse.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequest.java
> #1174 - copy request and response to/from map

- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerApplication.java
- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
> #1178 - Http server start and return deployed app

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpSessionManagerTest.java
> Fixes issue #1175 - Cannot set tracking mode with SSL and other methods

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranhaBuilder.java
- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- extension/micro-core/src/main/java/cloud/piranha/micro/core/PiranhaBeanArchiveHandler.java
- micro/src/main/java/cloud/piranha/micro/MicroConfiguration.java
- nano/src/main/java/cloud/piranha/nano/NanoPiranhaBuilder.java
- resource/impl/src/main/java/cloud/piranha/resource/DefaultResourceManager.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreInitializer.java
- session/hazelcast/src/main/java/cloud/piranha/session/hazelcast/HazelcastHttpSessionManager.java
- transaction/nonxa/src/main/java/cloud/piranha/transaction/nonxa/DefaultTransaction.java
- upload/apache/src/main/java/cloud/piranha/upload/apache/ApacheMultiPartManager.java
- webapp/annotationscan/src/main/java/cloud/piranha/webapp/annotationscan/AnnotationScanInitializer.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAnnotationManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpRequestManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletEnvironment.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationExtensionContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
- webapp/webannotation/src/main/java/cloud/piranha/webapp/webannotation/WebAnnotationInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1180 - Sonar lambdas code smell

- .github/workflows/jakartaee8-samples.yml
- .gitmodules
- external/jakartaee8-samples/pom.xml
- external/jakartaee8-samples/src/it/invoker.properties
- external/pom.xml
> Fixes issue #891 Add Jakarta EE 8 TCK Samples to external directory for testing

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultErrorPageManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultErrorPageManagerTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcherTest.java
> Fixes issue #1183 - Add support for wrapped exceptions and for UnavailableException

- bom/pom.xml
> #1185 - Update exausia to 0.6

- appserver/impl/src/main/java/cloud/piranha/appserver/impl/DefaultWebApplicationServer.java
> #1187 - Use concurrent hashmap to store web app.s

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXml.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlManager.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/WebXmlManagerTest.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlInitializer.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1193 - Add initial processing of web-fragments

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultFilterEnvironment.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/FilterTest.java
> Fixes issue #1202 - Set classname when adding a Filter instance

- webapp/api/src/main/java/cloud/piranha/webapp/api/HttpSessionManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSession.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
> Fixes issue #1205 - Pass the old value to attribute listener when removing/updating the attribute

- session/hazelcast/src/main/java/cloud/piranha/session/hazelcast/HazelcastHttpSession.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/HttpSessionManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSession.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
> Fixes issue #1208 - Add support for HttpSessionBindingListener

- webapp/api/src/main/java/cloud/piranha/webapp/api/LocaleEncodingManager.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultLocaleEncodingManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXml.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletResponseTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1213 - Add processing for locale-encoding-mapping-list

- servlet/api/src/main/java/javax/servlet/ServletRequestWrapper.java
- servlet/api/src/main/java/javax/servlet/ServletResponseWrapper.java
- servlet/api/src/test/java/javax/servlet/ServletRequestWrapperTest.java
- servlet/api/src/test/java/javax/servlet/http/HttpServletResponseWrapperTest.java
> Fixes issue #1215 - Make sure setRequest/setResponse don't allow null

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
> Fixes issue #1217 - Make sure to set the character encoding at getWriter

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServlet.java
> Fixes issue #1219 - Fallback to getWriter at DefaultServlet

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> Fixes issue #1221 - Included request cannot change the headers

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultWebApplicationTest.java
> Fixes #1223 - Make sure setBufferSize throws IllegalStateException if the response was commited

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/DefaultHttpServletResponseTest.java
> Fixes issue #1225 - Add Content-Length header when setting the content length

- servlet/api/pom.xml
> Fixes issue #1237 - Compile Servlet API with Java 8

- .github/workflows/ext-tck-expression-language.yml
- external/tck/el/pom.xml
Fixes #1235 
Run the EL TCK with JDK 8
> Fixes issue #1235 - Run TCK using JDK 8

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServlet.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> Fixes issue #1242 - Fix include requests according to TCK

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/HttpServletResponseTest.java
> Fixes issue #1245 - sendRedirect without leading slash shouldn't be relative to the current servlet

- appserver/impl/pom.xml
- appserver/impl/src/main/java/module-info.java
- http/singlethread/pom.xml
- server/pom.xml
- server2/pom.xml
- webapp/impl/pom.xml
- webapp/impl/src/main/java/module-info.java
> Fixes issue #1262 - Remove http-impl dependency from webapp-impl

- http/grizzly/src/main/java/module-info.java
- http/impl/src/main/java/module-info.java
- http/jdk/src/main/java/module-info.java
- http/netty/src/main/java/module-info.java
- http/singlethread/src/main/java/module-info.java
- http/undertow/src/main/java/module-info.java
- server/pom.xml
- server/src/main/java/cloud/piranha/server/ServerPiranha.java
- server/src/main/java/module-info.java
- server2/pom.xml
- server2/src/main/java/cloud/piranha/server2/ServerPiranha.java
- server2/src/main/java/module-info.java
> Fixes issue #1264 - Load HTTP implementation via ServiceLoader

- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpServer.java
- http/undertow/src/main/java/module-info.java
> Fixes issue #1265 - Add HTTP/2 support for Undertow

- server/pom.xml
- server2/pom.xml
> Fixes issue #1273 - Allow change the HTTP implementation via profile

- pom.xml
> Fixes issue #1256 - Remove Sonar workaround

- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlParser.java
- webapp/webxml/src/main/java/cloud/piranha/webapp/webxml/WebXmlProcessor.java
> Fixes issue #1298 - Process session-config

- bom/pom.xml
> Fixes issue #1319 - Update Grizzly

- server/src/main/java/cloud/piranha/server/CrossContextWebApplication.java
- server/src/main/java/cloud/piranha/server/ServerPiranha.java
> Fixes issue #1321 - Add support for cross-context

- bom/pom.xml
> Fixes issue #1329 - Update Tyrus

- bom/pom.xml
- faces/mojarra/src/main/java/cloud/piranha/faces/mojarra/MojarraInitializer.java
- test/hazelcast/src/main/webapp/WEB-INF/web.xml
- test/pom.xml
> Fixes issue #1331 - Migrate test/hazelcast to Servlet 5 / Jakarta EE 9

- test/exousia/src/test/java/cloud/piranha/test/exousia/BasicConnectionTest.java
- test/pom.xml
> Fixes issue #1333 - Migrate test/exousia to Servlet 5 / Jakarta EE 9

- test/jpa/pom.xml
- test/jpa/src/main/java/cloud/piranha/test/jpa/JPABean.java
- test/jpa/src/main/java/cloud/piranha/test/jpa/JPATable.java
- test/jpa/src/main/resources/META-INF/persistence.xml
- test/pom.xml
> Fixes #1335 - Migrate test/jpa to Servlet 5 / Jakarta EE 9

- faces/myfaces/src/main/java/cloud/piranha/faces/myfaces/MyFacesInitializer.java
- test/myfaces/src/main/webapp/WEB-INF/web.xml
- test/pom.xml
> Fixes issue #1339 - Migrate test/myfaces to Servlet 5 / Jakarta EE 9

- test/pom.xml
- test/weld/pom.xml
- test/weld/src/main/java/cloud/piranha/test/weld/WeldRequestBean.java
- test/weld/src/main/webapp/WEB-INF/web.xml
> Fixes issue #1341 - Migrate test/weld to Servlet 5 / Jakarta EE 9

- bom/pom.xml
- pages/jasper/pom.xml
- pages/jasper/src/test/java/module-info.java
> Fixes issue #1342 - Downgrade jakarta.el-api to allow Piranha Server startup using JPMS

- external/tck/servlet/pom.xml
> Fixes issue #1323 - Migrate Servlet TCK workflow to use the new Servlet 5 TCK

- bom/pom.xml
> Fixes issue #1345 - Update to latest Jakarta Expression Language release

- external/tck/pages/pom.xml
> Fixes issue #1347 - Migrate Pages TCK workflow to use the new Pages 3 TCK

- test/pom.xml
> Fixes issue #1350 - Re-enable some tests

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/DefaultWebApplicationTest.java
> Fixes issue #1352 - ServletContext.getMajorVersion should return 5

- pom.xml
- servlet/api/src/main/java/jakarta/servlet/ServletRequest.java
> Fixes issue #1354 - Add @Deprecated to ServletRequest.getRealPath

- http/api/src/main/java/cloud/piranha/http/api/HttpServerRequest.java
- http/grizzly/src/main/java/cloud/piranha/http/grizzly/GrizzlyHttpServerRequest.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerRequest.java
- http/jdk/src/main/java/cloud/piranha/http/jdk/JdkHttpRequest.java
- http/netty/src/main/java/cloud/piranha/http/netty/NettyHttpServerRequest.java
- http/tests/src/main/java/cloud/piranha/http/tests/HttpServerTest.java
- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpRequest.java
- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
> Fixes issue #1364 - Process HTTP protocol from the request

- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerApplication.java
- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- servlet/api/src/main/java/jakarta/servlet/http/Cookie.java
- servlet/api/src/test/java/jakarta/servlet/http/CookieTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/CookieParser.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/CookieParserTest.java
> Fixes #1362 - Validate HttpWebApplicationServer.processCookies against Servlet TCK

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/DefaultServletRequestDispatcherTest.java
> Fixes issue #1374 - Unwrap ServletException when setting the error attributes

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/DefaultServletRequestDispatcherTest.java
Reverts piranhacloud/piranha#1378
Fixes #1382
> Revert "Fixes issue #1374 - Unwrap ServletException when setting the error attributes"

- cli/pom.xml
- embedded/pom.xml
- http/jdk/pom.xml
- http/nano/pom.xml
- http/webapp/pom.xml
- naming/api/pom.xml
- naming/impl/pom.xml
- naming/thread/pom.xml
- pages/jasper/pom.xml
- policy/api/pom.xml
- policy/impl/pom.xml
- policy/pom.xml
- policy/thread/pom.xml
- pom.xml
> Tidying poms a little

- cdi/weld/src/main/java/module-info.java
> Fixes issue #1396 - Provide Weld service implementations via module-info

- bom/pom.xml
- extension/micro-core/pom.xml
- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- http/webapp/pom.xml
- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- http/webapp/src/main/java/module-info.java
- http/webapp/src/test/java/module-info.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/AuthorizationPreInitializer.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/PiranhaToExousiaConverter.java
- security/jakarta/src/main/java/cloud/piranha/security/jakarta/JakartaSecurityManager.java
* Make classes avaible
* Start the JNDI scope
* Fix security classes overwritten with old ones
* Update Exousia
> #1318 Fixes Micro startup

- bom/pom.xml
> Update several dependencies to latest

- servlet/api/pom.xml
> #1404 Add profile for Eclipse to solve split compile issue for it

- http/grizzly-test/pom.xml
- http/pom.xml
- http/webapp-test/pom.xml
- pages/jasper-test/pom.xml
- pages/pom.xml
- webapp/impl-test/pom.xml
- webapp/pom.xml
- webapp/webxml-test/pom.xml
Fixes #1410 
By default included. Build with -P-test-modules to exclude.
> #1410 Move test modules to test-modules profile

- arquillian/server/src/main/java/module-info.java
- microprofile/omnifaces/jwt/src/main/java/module-info.java
> Fixes issue #1416 - Provide missing service implementations via module-info

- bom/pom.xml
- extension/micro/pom.xml
- extension/webprofile/pom.xml
- external/tck/pages/pom.xml
- nano/pom.xml
- pages/wasp-tests/pom.xml
- pages/wasp/pom.xml
- pages/wasp/src/main/java/module-info.java
- test/hazelcast/pom.xml
- test/jpa/pom.xml
- test/mojarra/pom.xml
- test/myfaces/pom.xml
- test/weld/pom.xml
> Fixes issue #1419 - Change dependency from Jasper to WaSP

- resource/impl/src/main/java/cloud/piranha/resource/JarResource.java
> Fixes issue #1418 - Fix JarResource to properly close the JarFile used in getAllLocations

- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- micro/src/main/java/cloud/piranha/micro/MicroInfo.java
- micro/src/main/java/cloud/piranha/micro/MicroOuterDeployer.java
- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/ShrinkWrapResource.java
> #1422 Fix in Micro for accessing resources in jars

- external/jakartaee-samples/pom.xml
> #1424 - Add pom to run Jakarta EE samples

- .github/workflows/ext-jakartaee-samples.yml
- external/pom.xml
> #1426 Run Jakarta Samples

- resource/impl/src/main/java/cloud/piranha/resource/StringResource.java
> #1451 Add StringResource

- resource/impl/src/main/java/cloud/piranha/resource/ByteArrayResource.java
- resource/impl/src/main/java/cloud/piranha/resource/ByteArrayResourceStreamHandlerProvider.java
- resource/impl/src/main/java/module-info.java
- resource/impl/src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider
> #1453 Provide handler for bytes:// protocol used by ByteArrayResource

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranha.java
- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranhaBuilder.java
> #1455 Add support for bytearray resources to Embedded

- test/mojarra/src/test/java/cloud/piranha/test/faces/mojarra/MojarraTest.java
> #1459 Test for byte array based resources using Mojarra and embedded

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranhaBuilder.java
> #1462 Add methods directlt taking Class to EmbeddedPiranhaBuilder

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranha.java
- micro-embedded/pom.xml
- micro-embedded/src/main/java/cloud/piranha/micro/embedded/MicroEmbeddedPiranha.java
- micro-embedded/src/main/java/cloud/piranha/micro/embedded/MicroEmbeddedPiranhaBuilder.java
- micro-embedded/src/main/java/cloud/piranha/micro/embedded/MicroPiranhaBuilder.java
- micro-embedded/src/main/java/cloud/piranha/micro/embedded/MicroWebApplication.java
- micro-embedded/src/main/java/cloud/piranha/micro/embedded/package-info.java
- micro-embedded/src/main/java/module-info.java
- pom.xml
- server2/pom.xml
- server2/src/main/java/cloud/piranha/server2/ServerPiranha.java
- test/mojarra2/pom.xml
- test/mojarra2/src/test/java/cloud/piranha/test/faces/mojarra/Mojarra2Test.java
- test/pom.xml
> #1465 Add code to make Micro a bit easier to embed by end users.

- pom.xml
- test/mojarra2/src/test/java/cloud/piranha/test/faces/mojarra/Mojarra2Test.java
> Fixes issue #1470 - Add --illegal-access=permit to run the tests

- blog/2021/20210128_Modular_applications_with_JPMS
Fixes #1414
Feedbacks are welcome :)
> Fixes issue #1414 - Blog entry for the modular feature

- modular/modular/src/main/java/cloud/piranha/modular/DefaultModuleFinder.java
> Fixes issue #1504 - Supply all the packages when module-info only exports some of them

- pom.xml
> Fixes issue #1502 - Update Checkstyle version

- external/tck/servlet/pom.xml
> Fixes issue #1514 - Update Servlet TCK

- pom.xml
> Fixes issue #1516 - Add Thiago to the developers section of our POM

- http/grizzly/src/main/java/cloud/piranha/http/grizzly/GrizzlyHttpServer.java
> Fixes issue #1522 - Fix async TCK tests using Grizzly

- webapp/impl-test/src/test/java/cloud/piranha/webapp/impl/tests/DefaultWebApplicationRequestTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> Fixes issue #1526 - Process form parameters with charset defined

- webapp/impl-test/src/test/java/cloud/piranha/webapp/impl/tests/DefaultHttpServletRequestTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> Fixes issue #1531 - Use the new session id when calling HttpServletRequest::changeSessionId

- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- test/unit/http-webapp/src/test/java/cloud/piranha/test/unit/http/webapp/HttpWebApplicationServerTest.java
> Fixes issue #1533 - Use requested session id from URL

- external/tck/el/pom.xml
- external/tck/pages/pom.xml
- external/tck/servlet/pom.xml
> Fixes issue #1535 - Update Apache Ant used in the TCKs

- .github/workflows/ext-tck-expression-language.yml
- .github/workflows/ext-tck-pages.yml
> Fixes issue #1537 - Add manual trigger to TCK pipeline

- test/arquillian/pom.xml
- test/arquillian/servlet-basic/pom.xml
> Enable arquillian based test again

- extension/pom.xml
- http/grizzly/pom.xml
- http/jdk/pom.xml
- http/netty/pom.xml
- http/pom.xml
- http/undertow/pom.xml
- micro/builder/pom.xml
- micro/distribution/pom.xml
- micro/loader/pom.xml
- micro/pom.xml
- modular/modular/pom.xml
- modular/pom.xml
- server/pom.xml
- server2/pom.xml
- test/mojarra2/pom.xml
- test/unit/http-grizzly/pom.xml
- test/unit/http-impl/pom.xml
- test/unit/http-jdk/pom.xml
- test/unit/http-netty/pom.xml
- test/unit/http-tests/pom.xml
- test/unit/http-undertow/pom.xml
- test/unit/http-webapp/pom.xml
- test/unit/pom.xml
- test/unit/webapp-webxml/pom.xml
> Tidying poms

- bom/pom.xml
> #1541 Update Exousia to 1.1

- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroOuterDeployer.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationClassLoader.java
> Fixes issue #1543 - Use the MultiReleaseResource

- micro/distribution/pom.xml
> Fixes issue #1545 - Remove unnecessary access flags for Exousia

- external/tck/servlet/pom.xml
> Fixes issue #1557 - Enable SSL endpoint when running the TCK

- security/file/src/main/java/module-info.java
- security/file/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
> Fixes issue #1560 - Add FileSecurityInitilizer service information

- .github/workflows/build.yml
- .github/workflows/ext-jakartaee-samples.yml
- .github/workflows/ext-jakartaee8-samples.yml
- .github/workflows/ext-tck-expression-language.yml
- .github/workflows/ext-tck-microprofile-jwt.yml
- .github/workflows/ext-tck-pages.yml
- .github/workflows/ext-tck-servlet.yml
- .github/workflows/javadoc.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- maven/plugins/micro/pom.xml
- pom.xml
- servlet/api/pom.xml
> Fixes issue #1487 - Update workflows to Java 16 when it is released

- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroConfiguration.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroOuterDeployer.java
- modular/modular/src/main/java/cloud/piranha/modular/DefaultModuleFinder.java
- resource/impl/src/main/java/cloud/piranha/resource/JarResource.java
- security/exousia/src/main/java/cloud/piranha/security/exousia/PiranhaPrincipalMapper.java
- server/src/main/java/cloud/piranha/server/ServerPiranha.java
- webapp/impl-test/src/test/java/cloud/piranha/webapp/impl/tests/WebXmlManagerTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAnnotationManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlManager.java
> Fixes issue #1548 - Use the Stream::toList method

- webapp/impl-test/src/test/java/cloud/piranha/webapp/impl/tests/DefaultWebApplicationExtensionContextTest.java
- webapp/impl-test/src/test/java/cloud/piranha/webapp/impl/tests/ListenerTest.java
> Fixes issue #1565 - Change inner test classes to public

- bom/pom.xml
This includes the multi algo jar scanner.
Fixes #1568
> Update WaSP to 3.0.2

- pages/wasp/src/main/java/cloud/piranha/pages/wasp/WaspExtension.java
- pages/wasp/src/main/java/cloud/piranha/pages/wasp/WaspInitializer.java
- pages/wasp/src/main/java/cloud/piranha/pages/wasp/WaspJspManager.java
- pages/wasp/src/main/java/cloud/piranha/pages/wasp/WaspServlet.java
This is done by the following setting:
```java
servletContext.setAttribute("org.glassfish.wasp.useMultiJarScanAlgo", true);
```
Also done a few small cleanups.
Fixes #1569
> Activate WaSP multi-algo jar scanning.

- extension/micro/pom.xml
- extension/micro/src/main/java/cloud/piranha/extension/micro/MicroExtension.java
- extension/micro/src/main/java/module-info.java
> #1571 Activate WaSP for Piranha Micro

- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldCDI.java
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldContainer.java
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldProvider.java
> Small refactoring for Weld code.

- resource/impl/src/main/java/cloud/piranha/resource/DefaultResourceManagerClassLoader.java
> #1574 Try context class loader as option when class not found.

- resource/shrinkwrap/src/main/java/cloud/piranha/resource/shrinkwrap/GlobalArchiveStreamHandler.java
> #1578 Resolve global (shrinkwrap) URLs also against context class loader

- extension/micro/pom.xml
> Fixes issue #1576 - Exclude jakarta.servlet-api from JSTL dependency

- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
> #1580 Add support for Servlet's HandlesTypes in Micro.

- extension/micro-core/src/main/java/cloud/piranha/micro/core/PiranhaBeanArchiveHandler.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroOuterDeployer.java
> 1582 weld bean archives

- test/mojarra2/src/test/java/cloud/piranha/test/faces/mojarra/Mojarra2Test.java
> Fixes issue #1584 - Enable Mojarra test

- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranha.java
- naming/impl/src/main/java/cloud/piranha/naming/impl/DefaultInitialContext.java
- nano/src/main/java/cloud/piranha/nano/NanoPiranha.java
- servlet/api/src/main/java/jakarta/servlet/http/HttpFilter.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultAsyncContext.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultSecurityManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
Hello everyone,
This is my first contribution to the repository and I hope that it won't be the last!
I would love to have my code reviewed thoroughly as I would be happy to make any changes if they are needed.
These are all the instances that I could find in the existing codebase where we could take advantage of this new feature.
Thanks,
Jafer
> Fixes issue #1563 - Use pattern variables

- arquillian/server/src/main/java/cloud/piranha/arquillian/server/PiranhaServerDeployableContainer.java
- extension/micro-core/src/main/java/cloud/piranha/micro/core/MicroInnerDeployer.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroConfiguration.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroDeployOutcome.java
> #1592 Add option to use war base file name as context root in Micro

- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> #1594 Several fixes to the welcome page code

- bom/pom.xml
> Update Weld to 4.0.1

- bom/pom.xml
> #1598 Update Undertow to 2.2.5.Final

- bom/pom.xml
> #1602 Update SmallRye Config to 2.2.0

- bom/pom.xml
> #1604 Update OWB to 2.0.22

- arquillian/pom.xml
- bom/pom.xml
- cli/pom.xml
> #1606 Update test dependencies

- bom/pom.xml
> Update various example versions

- micro/distribution/pom.xml
- micro/loader/pom.xml
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroOuterDeployer.java
> Fixes issue #1600 - Remove unnecessary access flags for Weld

- extension/apache-fileupload/src/main/java/cloud/piranha/extension/apache/fileupload/ApacheMultiPartManager.java
- extension/apache-fileupload/src/test/java/cloud/piranha/extension/apache/fileupload/ApacheMultiPartManagerTest.java
- security/eleos/src/main/java/cloud/piranha/security/eleos/AuthenticationInitializer.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/AsyncHttpDispatchWrapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> #1616 Use multipart config

- external/omnifaces/pom.xml
> #1618 Adding OmniFaces tests as external test

- .github/workflows/ext-omnifaces.yml
- external/pom.xml
> #1620 Add workflow for omnifaces tests

- bom/pom.xml
- cli/pom.xml
- cli/src/main/java/cloud/piranha/cli/Cli.java
- cli/src/main/java/cloud/piranha/cli/NanoCli.java
- cli/src/main/java/cloud/piranha/cli/NanoCloudBuildCli.java
- cli/src/main/java/cloud/piranha/cli/NanoCloudCli.java
- cli/src/main/java/cloud/piranha/cli/NanoCloudDeployCli.java
- cli/src/main/java/cloud/piranha/cli/NanoGenerateCli.java
- cli/src/main/java/module-info.java
> Fixes issue #1589 - Use Picocli as argument parser - Piranha CLI

- .github/workflows/build.yml
> Fixes issue #1638 - Disable fail-fast feature of build workflow

- servlet/api/pom.xml
- servlet/api/src/main/java/jakarta/servlet/http/HttpFilter.java
> Fixes issue #1678 - Fix signature TCK test

- .github/workflows/ext-omnifaces.yml
> Fixes issue #1685 - Fix Omnifaces workflow

- cdi/weld/src/main/java/cloud/piranha/cdi/weld/RealtimeHttpServletRequestWrapper.java
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldCDI.java
- cdi/weld/src/main/java/cloud/piranha/cdi/weld/WeldProvider.java
- embedded/src/main/java/cloud/piranha/embedded/EmbeddedPiranha.java
- embedded/src/main/java/cloud/piranha/embedded/EmbeddedResponse.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServer.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServerRequest.java
- http/api/src/main/java/cloud/piranha/http/api/HttpServerResponse.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServer.java
- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpServer.java
- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- micro/builder/src/main/java/cloud/piranha/micro/embedded/MicroEmbeddedPiranha.java
- micro/builder/src/main/java/cloud/piranha/micro/embedded/MicroWebApplication.java
- micro/core/src/main/java/cloud/piranha/micro/core/InMemoryIdentityStore.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroConfiguration.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/MicroDeployOutcome.java
- micro/loader/src/main/java/cloud/piranha/micro/loader/StaticURLStreamHandlerFactory.java
- pom.xml
- test/jpa/src/main/java/cloud/piranha/test/jpa/JPABean.java
- test/jpa/src/main/java/cloud/piranha/test/jpa/JPATable.java
Hello everyone,
This pull request affects files in the following modules (and the project's POM file) for the inline return tag:
```
jpa
piranha-cdi-weld
piranha-embedded
piranha-http-api
piranha-http-impl
piranha-http-undertow
piranha-http-webapp
piranha-micro-builder
piranha-micro-core
piranha-micro-loader
```
I will be creating similar small pull requests that cover other modules as well.
Thanks,
Jafer
> #1500 - Simplify JavaDocs

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/DefaultHttpServletResponseTest.java
> #1701 setLocale should only set charencoding when not set yet

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> #1661 Fixed several requirements for response.

- servlet/api/pom.xml
- servlet/pom.xml
- servlet/quicklook/pom.xml
> #1707 QuickLook tests for Servlet

- servlet/pom.xml
- test/pom.xml
- test/quicklook/pom.xml
> #1710 Move quicklook to right location

- .github/workflows/ext-tck-pages.yml
- external/tck/pages/pom.xml
> Fixes issue #1716 - Update Pages TCK

- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequestMapping.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapping.java
> #1720 - Add matchValue to request mapping

- test/embedded/bootstrap/src/test/java/test/embedded/bootstrap/BootstrapTest.java
- webapp/api/src/main/java/cloud/piranha/webapp/api/WebApplicationRequestMapper.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequestMapper.java
> #1725 - Added support for detecting default HttpServletMapping

- webapp/api/src/main/java/cloud/piranha/webapp/api/ServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultInvocationFinder.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletInvocation.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1727 Set correct HttpServletMapping for named dispatches

- pom.xml
> Fixes issue #1735 - Update Checkstyle

- servlet/api/src/main/java/jakarta/servlet/http/HttpServletRequestWrapper.java
- servlet/api/src/test/java/jakarta/servlet/http/HttpServletRequestWrapperTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1730 - support http servlet mapping for include from named dispatch

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> #1740 - Fix condition - includes should always have mapping of includer

- pom.xml
> Fixes issue #1611 - Remove --illegal-access flag from Surefire and Failsafe

- test/webapp/helloworld/src/main/webapp/index.html
- Updated the html header with the language attribute
- This commit will resolve the sonar issue.
> Added the language attribute for html for Issue #1784

- extension/exousia/src/main/java/cloud/piranha/extension/exousia/PiranhaToExousiaConverter.java
- extension/soteria/src/main/java/cloud/piranha/extension/soteria/SoteriaPreCDIInitializer.java
- extension/webxml/src/main/java/cloud/piranha/extension/webxml/WebXmlParser.java
- extension/webxml/src/main/java/cloud/piranha/extension/webxml/WebXmlProcessor.java
- extension/webxml/src/test/java/cloud/piranha/extension/webxml/tests/WebXmlParserTest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlContextParam.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlCookieConfig.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlErrorPage.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlFilterInitParam.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlListener.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlLoginConfig.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlMimeMapping.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServletInitParam.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServletMapping.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlServletSecurityRoleRef.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/WebXmlSessionConfig.java
Fixes #1800 
Convert WebXml* classes to records
> Fixes issue #1800  - Convert WebXml classes to records

- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerRequest.java
- http/jdk/src/main/java/cloud/piranha/http/jdk/JdkHttpRequest.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> Fixes issue #1839 - Avoid looking for standard encodings

- servlet/api/src/main/java/jakarta/servlet/http/Cookie.java
> Fixes issue #1853 - Fix Signature test

- servlet/api/src/main/java/jakarta/servlet/ServletRequestWrapper.java
- servlet/api/src/main/java/jakarta/servlet/ServletResponseWrapper.java
- servlet/api/src/test/java/jakarta/servlet/AsyncEventTest.java
- servlet/api/src/test/java/jakarta/servlet/ServletRequestEventTest.java
- servlet/api/src/test/java/jakarta/servlet/ServletRequestWrapperTest.java
- servlet/api/src/test/java/jakarta/servlet/TestServletRequest.java
- servlet/api/src/test/java/jakarta/servlet/http/HttpServletRequestWrapperTest.java
- servlet/api/src/test/java/jakarta/servlet/http/HttpServletResponseTest.java
- servlet/api/src/test/java/jakarta/servlet/http/HttpServletResponseWrapperTest.java
- servlet/api/src/test/java/jakarta/servlet/http/TestHttpServletRequest.java
- servlet/api/src/test/java/jakarta/servlet/http/TestHttpServletResponse.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultServletRequestDispatcher.java
> Fixes issue #1858 - ServletRequest/ResponseWrapper shouldn't accept null as wrapper

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSession.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplication.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationRequest.java
> Fixes issue #1872 - Set last accessed time after the request finishes

- extension/webxml/src/main/java/cloud/piranha/extension/webxml/WebXmlProcessor.java
- http/impl/src/main/java/cloud/piranha/http/impl/DefaultHttpServerResponse.java
- http/undertow/src/main/java/cloud/piranha/http/undertow/UndertowHttpRequest.java
- http/webapp/src/main/java/cloud/piranha/http/webapp/HttpWebApplicationServer.java
- resource/impl/src/main/java/cloud/piranha/resource/DefaultResourceManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpHeaderManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultWebApplicationResponse.java
> Fixes issue #1879 - Replace 'while' cycles with iterator with enhanced-for

- extension/webannotations/src/test/java/cloud/piranha/extension/webannotations/tests/WebServletTest.java
- extension/webxml/src/test/java/cloud/piranha/extension/webxml/tests/LocaleEncodingMappingListTest.java
- extension/webxml/src/test/java/cloud/piranha/extension/webxml/tests/WithoutLeadingSlashTest.java
- naming/impl/src/test/java/cloud/piranha/naming/impl/DefaultNamingManagerTest.java
- naming/thread/src/test/java/cloud/piranha/naming/thread/ThreadInitialContextFactoryTest.java
- nano/src/test/java/cloud/piranha/nano/NanoServletConfigTest.java
- policy/impl/src/test/java/cloud/piranha/policy/impl/tests/DefaultPolicyManagerTest.java
- policy/thread/pom.xml
- policy/thread/src/test/java/cloud/piranha/policy/thread/tests/ThreadPolicyTest.java
- policy/thread/src/test/java/module-info.java
- servlet/api/src/test/java/jakarta/servlet/http/CookieTest.java
- webapp/impl/src/test/java/cloud/piranha/webapp/impl/tests/SessionCookieConfigTest.java
> Fixes issue #1882 - Remove public modifier from tests

- webapp/impl/src/main/java/cloud/piranha/webapp/impl/DefaultHttpSessionManager.java
> Fixes issue #1875 - Cookies are being rejected when using request dispatcher

- pom.xml
> Fixes issue #1888 - Update Checkstyle
